#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

user="test"
repository="$(basename $(dirname $(pwd)))"
ansible_version="7.2.0"

image="ubuntu"
ubuntu_releases=(jammy kinetic)
for tag in "${ubuntu_releases[@]}"; do
    dir="${tag}"
    mkdir -p "${dir}"
    echo "*** Updating $dir/Dockerfile"
    sed -r \
        -e 's!%%FROM%%!'"$image:$tag"'!g' \
        -e 's!%%USER%%!'"$user"'!g' \
        -e 's!%%REPOSITORY%%!'"$repository"'!g' \
        -e 's!%%ANSIBLE_VERSION%%!'"$ansible_version"'!g' \
        "Dockerfile.template" > "$dir/Dockerfile"
done

image="debian"
debian_releases=(bullseye bookworm)
for tag in "${debian_releases[@]}"; do
    dir="${tag}"
    mkdir -p "${dir}"
    echo "*** Updating $dir/Dockerfile"
    sed -r \
        -e 's!%%FROM%%!'"$image:$tag"'!g' \
        -e 's!%%USER%%!'"$user"'!g' \
        -e 's!%%REPOSITORY%%!'"$repository"'!g' \
        -e 's!%%ANSIBLE_VERSION%%!'"$ansible_version"'!g' \
        "Dockerfile.template" > "$dir/Dockerfile"
done
