name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        ansible --version
        printf '[defaults]\nroles_path=../\n' > ansible.cfg
        ansible-playbook tests/test.yml -i tests/inventory --syntax-check
        ansible-playbook tests/test.yml -i tests/inventory --connection=local -e "{'linuxbrew_use_installer':true}"
